// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gztjiknpddlkcxuavoeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dGppa25wZGRsa2N4dWF2b2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzcwODQsImV4cCI6MjA3NDIxMzA4NH0.CFkXaIGhRYhRojGIstCtqhIJoKTMLgDHk2LB0Q8Pt-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});